"""Typed handler in, JSON tool schema out. FR-TOOL-01.

The schema is generated by pydantic from the handler's own signature, so a tool's contract and
its implementation cannot drift: there is only one declaration of either.
"""

from __future__ import annotations

import inspect
from collections.abc import Callable, Iterable, Iterator
from typing import Any, get_type_hints, overload

from pydantic import BaseModel, ValidationError, create_model

Handler = Callable[..., Any]


class ToolNotFound(LookupError):
    """FR-TOOL-01 — a name the registry does not have, never a `KeyError`.

    Carries `available` because FR-AGENT-05 has to turn this into a tool message that lists the
    tools the model *could* have called.
    """

    def __init__(self, name: str, available: list[str]) -> None:
        self.name = name
        self.available = available
        super().__init__(
            f"unknown tool {name!r}. Available tools: {', '.join(available) or '(none)'}"
        )


class Tool:
    """One callable the model may invoke, plus the schema that describes it."""

    def __init__(
        self, handler: Handler, *, name: str | None = None, description: str | None = None
    ):
        self.handler = handler
        self.name = name or handler.__name__
        self.description = (description or inspect.getdoc(handler) or "").strip()
        if not self.description:
            raise ValueError(
                f"tool {self.name!r} has no description — give the handler a docstring. The "
                "description is what the model chooses on."
            )
        self.args_model = _args_model(handler, self.name)

    @property
    def summary(self) -> str:
        """First paragraph of the docstring — the one line the schema carries."""
        return self.description.split("\n\n", 1)[0].strip()

    def parameters(self) -> dict[str, Any]:
        schema = self.args_model.model_json_schema()
        schema.pop("title", None)
        for prop in schema.get("properties", {}).values():
            prop.pop("title", None)
        schema.setdefault("properties", {})
        schema.setdefault("required", [])
        return schema

    def spec(self) -> dict[str, Any]:
        """The OpenAI-shaped tool definition every provider litellm fronts accepts."""
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.summary,
                "parameters": self.parameters(),
            },
        }

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<Tool {self.name}>"


#: What `@tool(...)` returns before it is applied to a handler.
Decorator = Callable[[Handler], Tool]


@overload
def tool(fn: Handler) -> Tool: ...


@overload
def tool(*, name: str | None = ..., description: str | None = ...) -> Decorator: ...


def tool(
    fn: Handler | None = None,
    *,
    name: str | None = None,
    description: str | None = None,
) -> Tool | Decorator:
    """Decorator, bare or called: `@tool` and `@tool(name="run_bash")` both work.

    Overloaded rather than `-> Any` so that a decorated handler is statically a `Tool` and
    mypy keeps checking the module that defines it.
    """
    if fn is not None:
        return Tool(fn, name=name, description=description)

    def wrap(inner: Handler) -> Tool:
        return Tool(inner, name=name, description=description)

    return wrap


def _args_model(handler: Handler, name: str) -> type[BaseModel]:
    """A pydantic model of the handler's parameters. Doubles as validator and as schema."""
    signature = inspect.signature(handler)
    hints = get_type_hints(handler, include_extras=True)
    fields: dict[str, Any] = {}
    for pname, param in signature.parameters.items():
        if pname in {"self", "cls"} or param.kind in {
            inspect.Parameter.VAR_POSITIONAL,
            inspect.Parameter.VAR_KEYWORD,
        }:
            continue
        annotation = hints.get(pname, str)
        default = ... if param.default is inspect.Parameter.empty else param.default
        fields[pname] = (annotation, default)
    # Extra keys are ignored rather than forbidden: a stray argument is not worth failing a call
    # the model otherwise got right, and a *misspelled* required one still fails as missing.
    return create_model(f"{name}_args", **fields)


class ToolRegistry:
    """The set of tools one phase may call. Constructing it is the security boundary:
    Shape A phases (SEC-03) simply never receive the filesystem and bash tools."""

    def __init__(self, tools: Iterable[Tool] = ()) -> None:
        self._tools: dict[str, Tool] = {}
        for t in tools:
            self.add(t)

    def add(self, t: Tool) -> Tool:
        if t.name in self._tools:
            raise ValueError(f"tool {t.name!r} is already registered")
        self._tools[t.name] = t
        return t

    @property
    def names(self) -> list[str]:
        return list(self._tools)

    def get(self, name: str) -> Tool:
        try:
            return self._tools[name]
        except KeyError:
            raise ToolNotFound(name, self.names) from None

    def specs(self) -> list[dict[str, Any]]:
        return [t.spec() for t in self._tools.values()]

    def __contains__(self, name: object) -> bool:
        return name in self._tools

    def __len__(self) -> int:
        return len(self._tools)

    def __iter__(self) -> Iterator[Tool]:
        return iter(self._tools.values())

    async def execute(self, name: str, arguments: dict[str, Any]) -> str:
        """Validate, dispatch, stringify.

        Bad arguments come back as a message the model can correct itself from. An exception
        *inside* a handler propagates — the loop frames it as a tool message (FR-AGENT-04), and
        a registry that swallowed it would hide bugs in the tools as well.
        """
        t = self.get(name)
        try:
            args = t.args_model(**arguments)
        except ValidationError as exc:
            return _argument_error(t, exc)
        kwargs = {field: getattr(args, field) for field in t.args_model.model_fields}
        result = t.handler(**kwargs)
        if inspect.isawaitable(result):
            result = await result
        return result if isinstance(result, str) else str(result)


def _argument_error(t: Tool, exc: ValidationError) -> str:
    lines = [f"ERROR: invalid arguments for `{t.name}`."]
    for error in exc.errors():
        where = ".".join(str(p) for p in error["loc"]) or "(root)"
        lines.append(f"- {where}: {error['msg']}")
    expected = ", ".join(
        f"{k}{'' if k in t.parameters()['required'] else ' (optional)'}"
        for k in t.parameters()["properties"]
    )
    lines.append(f"Expected arguments: {expected}")
    return "\n".join(lines)
